language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

before_script:
    - shellcheck --version

script:
    - shellcheck -e SC2034 duplicity-backup.sh duplicity-backup.conf.example

matrix:
  fast_finish: true
